name: marketing_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  vexana: ^4.0.1
  kartal: ^3.5.0
  sizer: ^2.0.15
  dio: ^5.4.1
  auto_route: ^7.9.0
  build_runner: ^2.3.2
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  salomon_bottom_bar: ^3.3.1
  font_awesome_flutter: ^10.2.1
  flutter_slidable: ^3.1.0
  flutter_image_slider: ^0.0.2
  flutter_image_slideshow: ^0.1.4
  flutter_bloc: ^8.1.1
  lottie: ^3.1.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_credit_card: ^4.0.1
  
dev_dependencies:
  auto_route_generator: ^7.3.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/
    - assets/svg/
